### ISSUE TITLE
Cannot use module in Julia 0.3.7

### ISSUE THREAD

**Issue by cuevasclemente** [iamed2/PostgreSQL.jl#9]
Perhaps this is intentional (this behaviour may be fixed in 0.4.x), but the module cannot be imported in Julia 0.3.7 (on OS X, with Julia installed with Homebrew). 

Looking into it has led me to believe that the reason why is in PostgreSQL.jl, the line 
    using DBI

Is causing Julia to attempt to import the contents of the file `dbi.jl`, rather than the module. I am not sure why this is the case. When I change the name of the file `dbi.jl` to something else, such as `dba.jl`, and chance the include line to 
    include("dba.jl")
The module imports successfully. Otherwise, I get the following error:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.7 (2015-03-23 21:36 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> using PostgreSQL
ERROR: Postgres not defined
 in include at /opt/homebrew-cask/Caskroom/julia/0.3.7/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /opt/homebrew-cask/Caskroom/julia/0.3.7/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at /opt/homebrew-cask/Caskroom/julia/0.3.7/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /opt/homebrew-cask/Caskroom/julia/0.3.7/Julia-0.3.7.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/user/.julia/v0.3/PostgreSQL/src/DBI.jl, in expression starting on line 1
while loading /Users/user/.julia/v0.3/PostgreSQL/src/PostgreSQL.jl, in expression starting on line 8
```

**Comment by iamed2** [comment]
This didn't affect my install but I've updated with a harmless fix.

**Comment by cuevasclemente** [comment]
The same issue occurs for me with "dataframes.jl", since it interacts with DBI's importing of `DataFrames`. What version of Julia are you running to test this?

**Comment by iamed2** [comment]
Worked with v0.3.7 on OS X.

**Comment by cuevasclemente** [comment]
I think I know what I'm doing differently: I was trying to use the module in my `/Users/user/.julia/v0.3/PostgreSQL/src/` directory.

**Comment by iamed2** [comment]
Ah. Maybe there is something I can do with includes so that can't happen.
